# Generated by Django 3.0.5 on 2024-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.PositiveIntegerField()),
                ('patientId', models.PositiveIntegerField()),
                ('patientName', models.CharField(max_length=40)),
                ('doctorName', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField()),
                ('payment_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
