# Generated by Django 3.0.5 on 2024-09-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_payment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_details',
        ),
    ]
