# Generated by Django 3.0.5 on 2024-09-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_delete_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/DoctorProfilePic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pic/PatientProfilePic/'),
        ),
    ]
